###
POST http://localhost:8080/user/sign-up
Content-Type: application/json

{
  "username": "Amirhossein",
  "password": "defaultPassword",
  "userType": "DESIGNER"
}


###
POST http://localhost:8080/category/add
Content-Type: application/json

{
  "name": "Geography",
  "description": "Geography questions"
}

###
POST http://localhost:8080/question/add
userId: 1
Content-Type: application/json

{
  "question": "What is the capital of Canada?",
  "option1": "Toronto",
  "option2": "Ottawa",
  "option3": "Vancouver",
  "option4": "Montreal",
  "correctOption": 2,
  "difficulty": "MEDIUM",
  "categoryId": 1
}

###
POST http://localhost:8080/question/my-questions
userId: 1
Content-Type: application/json

{
}

###
POST http://localhost:8080/user/sign-up
Content-Type: application/json

{
  "username": "Mahdi",
  "password": "defaultPassword",
  "userType": "PLAYER"
}

###

POST http://localhost:4000/user/login
Content-Type: application/json

{
"username": "Mahdi",
"password": "defaultPassword"
}
