###
POST http://localhost:4000/user/sign-up
Content-Type: application/json

{
  "username": "Erfan",
  "password": "password",
  "userType": "PLAYER"
}


###
POST http://localhost:4000/category/add
Content-Type: application/json

{
  "name": "Geography",
  "description": "Geography questions"
}

###
POST http://localhost:4000/question/designer/add
userId: 1
Content-Type: application/json

{
  "question": "What is the capital of Canada?",
  "option1": "Toronto",
  "option2": "Ottawa",
  "option3": "Vancouver",
  "option4": "Montreal",
  "correctOption": 2,
  "difficulty": "MEDIUM",
  "categoryId": 1
}

###
POST http://localhost:4000/question/designer/all
userId: 1
Content-Type: application/json

{
}

###
GET http://localhost:4000/category/all


###
POST http://localhost:4000/user/sign-up
Content-Type: application/json

{
  "username": "Mahdi",
  "password": "defaultPassword",
  "userType": "PLAYER"
}

###

POST http://localhost:4000/user/login
Content-Type: application/json

{
"username": "Mahdi",
"password": "password"
}

###
POST http://localhost:4000/question/player/all
userId: 2
Content-Type: application/json

{
}
###
GET http://localhost:4000/user/designer/all

###
GET http://localhost:4000/user/player/all

###
POST http://localhost:4000/user/player/follow-unfollow-player
userId: 2
Content-Type: application/json

{
  "username": "Sogand",
  "follow": true
}
